Here are the promised fixes to make freetype 2.5.0 buildable again:
freetype2.conf:
Two functions have been renamed, one has even a different signature.
I think it's OK to keep LVO because we are in ABIv1.

ftconfig.h:
disabled assembler code to fix this error:
.../aros-linux-i386-dbg/bin/linux-i386/gen/workbench/libs/freetype/src/freetype2_start.c:137:9: error: conflicting types for 'FT_MulFix_i386'
.../aros-src/workbench/libs/freetype/src/../include/freetype/config/ftconfig.h:405:3: note: previous definition of 'FT_MulFix_i386' was here

I didn't find a better solution.



git-svn-id: https://svn.aros.org/svn/aros/trunk@47879 fb15a70f-31f2-0310-bbcc-cdcc74a49acc